# Generated by Django 3.1.6 on 2021-03-03 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='userl',
        ),
    ]
