# Generated by Django 3.1.6 on 2021-03-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0002_remove_task_userl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='userl',
            new_name='user1',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('P', 'PENDING'), ('C', 'COMPLETED'), ('IP', 'IN_PROGRESS'), ('D', 'DROPPED')], default=('P', 'PENDING'), max_length=2),
        ),
    ]
